// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: route.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "route.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace DFMS {
namespace ROUTE {

namespace {

const ::google::protobuf::Descriptor* getLatestVersionRequest_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  getLatestVersionRequest_reflection_ = NULL;
const ::google::protobuf::Descriptor* getLatestVersionResponse_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  getLatestVersionResponse_reflection_ = NULL;
const ::google::protobuf::Descriptor* userLoginRequest_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  userLoginRequest_reflection_ = NULL;
const ::google::protobuf::Descriptor* userLoginResponse_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  userLoginResponse_reflection_ = NULL;
const ::google::protobuf::Descriptor* tFile_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  tFile_reflection_ = NULL;
const ::google::protobuf::Descriptor* getDirFilesNameRequest_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  getDirFilesNameRequest_reflection_ = NULL;
const ::google::protobuf::Descriptor* getDirFilesNameResponse_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  getDirFilesNameResponse_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* eFileType_descriptor_ = NULL;
const ::google::protobuf::EnumDescriptor* eFilePermis_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_route_2eproto() {
  protobuf_AddDesc_route_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "route.proto");
  GOOGLE_CHECK(file != NULL);
  getLatestVersionRequest_descriptor_ = file->message_type(0);
  static const int getLatestVersionRequest_offsets_[1] = {
  };
  getLatestVersionRequest_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      getLatestVersionRequest_descriptor_,
      getLatestVersionRequest::default_instance_,
      getLatestVersionRequest_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(getLatestVersionRequest, _has_bits_[0]),
      -1,
      -1,
      sizeof(getLatestVersionRequest),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(getLatestVersionRequest, _internal_metadata_),
      -1);
  getLatestVersionResponse_descriptor_ = file->message_type(1);
  static const int getLatestVersionResponse_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(getLatestVersionResponse, versionno_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(getLatestVersionResponse, versionupdatemsg_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(getLatestVersionResponse, errorcode_),
  };
  getLatestVersionResponse_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      getLatestVersionResponse_descriptor_,
      getLatestVersionResponse::default_instance_,
      getLatestVersionResponse_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(getLatestVersionResponse, _has_bits_[0]),
      -1,
      -1,
      sizeof(getLatestVersionResponse),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(getLatestVersionResponse, _internal_metadata_),
      -1);
  userLoginRequest_descriptor_ = file->message_type(2);
  static const int userLoginRequest_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(userLoginRequest, username_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(userLoginRequest, password_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(userLoginRequest, macaddress_),
  };
  userLoginRequest_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      userLoginRequest_descriptor_,
      userLoginRequest::default_instance_,
      userLoginRequest_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(userLoginRequest, _has_bits_[0]),
      -1,
      -1,
      sizeof(userLoginRequest),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(userLoginRequest, _internal_metadata_),
      -1);
  userLoginResponse_descriptor_ = file->message_type(3);
  static const int userLoginResponse_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(userLoginResponse, username_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(userLoginResponse, sessionid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(userLoginResponse, logintime_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(userLoginResponse, errorcode_),
  };
  userLoginResponse_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      userLoginResponse_descriptor_,
      userLoginResponse::default_instance_,
      userLoginResponse_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(userLoginResponse, _has_bits_[0]),
      -1,
      -1,
      sizeof(userLoginResponse),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(userLoginResponse, _internal_metadata_),
      -1);
  tFile_descriptor_ = file->message_type(4);
  static const int tFile_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(tFile, filename_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(tFile, filetype_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(tFile, filepermis_),
  };
  tFile_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      tFile_descriptor_,
      tFile::default_instance_,
      tFile_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(tFile, _has_bits_[0]),
      -1,
      -1,
      sizeof(tFile),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(tFile, _internal_metadata_),
      -1);
  getDirFilesNameRequest_descriptor_ = file->message_type(5);
  static const int getDirFilesNameRequest_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(getDirFilesNameRequest, reqid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(getDirFilesNameRequest, authuuid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(getDirFilesNameRequest, dirstr_),
  };
  getDirFilesNameRequest_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      getDirFilesNameRequest_descriptor_,
      getDirFilesNameRequest::default_instance_,
      getDirFilesNameRequest_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(getDirFilesNameRequest, _has_bits_[0]),
      -1,
      -1,
      sizeof(getDirFilesNameRequest),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(getDirFilesNameRequest, _internal_metadata_),
      -1);
  getDirFilesNameResponse_descriptor_ = file->message_type(6);
  static const int getDirFilesNameResponse_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(getDirFilesNameResponse, reqid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(getDirFilesNameResponse, dirstr_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(getDirFilesNameResponse, files_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(getDirFilesNameResponse, errorcode_),
  };
  getDirFilesNameResponse_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      getDirFilesNameResponse_descriptor_,
      getDirFilesNameResponse::default_instance_,
      getDirFilesNameResponse_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(getDirFilesNameResponse, _has_bits_[0]),
      -1,
      -1,
      sizeof(getDirFilesNameResponse),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(getDirFilesNameResponse, _internal_metadata_),
      -1);
  eFileType_descriptor_ = file->enum_type(0);
  eFilePermis_descriptor_ = file->enum_type(1);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_route_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      getLatestVersionRequest_descriptor_, &getLatestVersionRequest::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      getLatestVersionResponse_descriptor_, &getLatestVersionResponse::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      userLoginRequest_descriptor_, &userLoginRequest::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      userLoginResponse_descriptor_, &userLoginResponse::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      tFile_descriptor_, &tFile::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      getDirFilesNameRequest_descriptor_, &getDirFilesNameRequest::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      getDirFilesNameResponse_descriptor_, &getDirFilesNameResponse::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_route_2eproto() {
  delete getLatestVersionRequest::default_instance_;
  delete getLatestVersionRequest_reflection_;
  delete getLatestVersionResponse::default_instance_;
  delete getLatestVersionResponse_reflection_;
  delete userLoginRequest::default_instance_;
  delete userLoginRequest_reflection_;
  delete userLoginResponse::default_instance_;
  delete userLoginResponse_reflection_;
  delete tFile::default_instance_;
  delete tFile_reflection_;
  delete getDirFilesNameRequest::default_instance_;
  delete getDirFilesNameRequest_reflection_;
  delete getDirFilesNameResponse::default_instance_;
  delete getDirFilesNameResponse_reflection_;
}

void protobuf_AddDesc_route_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\013route.proto\022\nDFMS.ROUTE\"\031\n\027getLatestVe"
    "rsionRequest\"Z\n\030getLatestVersionResponse"
    "\022\021\n\tversionNo\030\001 \001(\t\022\030\n\020versionUpdateMsg\030"
    "\002 \001(\t\022\021\n\terrorCode\030\003 \001(\r\"J\n\020userLoginReq"
    "uest\022\020\n\010username\030\001 \001(\t\022\020\n\010password\030\002 \001(\t"
    "\022\022\n\nmacAddress\030\003 \001(\t\"^\n\021userLoginRespons"
    "e\022\020\n\010username\030\001 \001(\t\022\021\n\tsessionId\030\002 \001(\t\022\021"
    "\n\tloginTime\030\003 \001(\004\022\021\n\terrorCode\030\004 \001(\r\"o\n\005"
    "tFile\022\020\n\010fileName\030\001 \001(\t\022\'\n\010fileType\030\002 \001("
    "\0162\025.DFMS.ROUTE.eFileType\022+\n\nfilePermis\030\003"
    " \001(\0162\027.DFMS.ROUTE.eFilePermis\"I\n\026getDirF"
    "ilesNameRequest\022\r\n\005reqId\030\001 \001(\r\022\020\n\010authUU"
    "ID\030\002 \001(\t\022\016\n\006dirStr\030\003 \001(\t\"m\n\027getDirFilesN"
    "ameResponse\022\r\n\005reqId\030\001 \001(\r\022\016\n\006dirStr\030\002 \001"
    "(\t\022 \n\005files\030\003 \003(\0132\021.DFMS.ROUTE.tFile\022\021\n\t"
    "errorCode\030\004 \001(\r*9\n\teFileType\022\014\n\010eDirType"
    "\020\000\022\014\n\010eDocType\020\001\022\020\n\014eGeneralType\020\002*B\n\013eF"
    "ilePermis\022\013\n\007eDenied\020\000\022\r\n\teReadOnly\020\001\022\016\n"
    "\neWriteOnly\020\002\022\007\n\003eRW\020\003", 742);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "route.proto", &protobuf_RegisterTypes);
  getLatestVersionRequest::default_instance_ = new getLatestVersionRequest();
  getLatestVersionResponse::default_instance_ = new getLatestVersionResponse();
  userLoginRequest::default_instance_ = new userLoginRequest();
  userLoginResponse::default_instance_ = new userLoginResponse();
  tFile::default_instance_ = new tFile();
  getDirFilesNameRequest::default_instance_ = new getDirFilesNameRequest();
  getDirFilesNameResponse::default_instance_ = new getDirFilesNameResponse();
  getLatestVersionRequest::default_instance_->InitAsDefaultInstance();
  getLatestVersionResponse::default_instance_->InitAsDefaultInstance();
  userLoginRequest::default_instance_->InitAsDefaultInstance();
  userLoginResponse::default_instance_->InitAsDefaultInstance();
  tFile::default_instance_->InitAsDefaultInstance();
  getDirFilesNameRequest::default_instance_->InitAsDefaultInstance();
  getDirFilesNameResponse::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_route_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_route_2eproto {
  StaticDescriptorInitializer_route_2eproto() {
    protobuf_AddDesc_route_2eproto();
  }
} static_descriptor_initializer_route_2eproto_;
const ::google::protobuf::EnumDescriptor* eFileType_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return eFileType_descriptor_;
}
bool eFileType_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* eFilePermis_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return eFilePermis_descriptor_;
}
bool eFilePermis_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}


namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD;
static void MergeFromFail(int line) {
  GOOGLE_CHECK(false) << __FILE__ << ":" << line;
}

}  // namespace


// ===================================================================

#ifndef _MSC_VER
#endif  // !_MSC_VER

getLatestVersionRequest::getLatestVersionRequest()
  : ::google::protobuf::Message() , _internal_metadata_(NULL)  {
  SharedCtor();
  // @@protoc_insertion_point(constructor:DFMS.ROUTE.getLatestVersionRequest)
}

void getLatestVersionRequest::InitAsDefaultInstance() {
}

getLatestVersionRequest::getLatestVersionRequest(const getLatestVersionRequest& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:DFMS.ROUTE.getLatestVersionRequest)
}

void getLatestVersionRequest::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

getLatestVersionRequest::~getLatestVersionRequest() {
  // @@protoc_insertion_point(destructor:DFMS.ROUTE.getLatestVersionRequest)
  SharedDtor();
}

void getLatestVersionRequest::SharedDtor() {
  if (this != default_instance_) {
  }
}

void getLatestVersionRequest::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* getLatestVersionRequest::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return getLatestVersionRequest_descriptor_;
}

const getLatestVersionRequest& getLatestVersionRequest::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_route_2eproto();
  return *default_instance_;
}

getLatestVersionRequest* getLatestVersionRequest::default_instance_ = NULL;

getLatestVersionRequest* getLatestVersionRequest::New(::google::protobuf::Arena* arena) const {
  getLatestVersionRequest* n = new getLatestVersionRequest;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void getLatestVersionRequest::Clear() {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool getLatestVersionRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:DFMS.ROUTE.getLatestVersionRequest)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0 ||
        ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
        ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormat::SkipField(
          input, tag, mutable_unknown_fields()));
  }
success:
  // @@protoc_insertion_point(parse_success:DFMS.ROUTE.getLatestVersionRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:DFMS.ROUTE.getLatestVersionRequest)
  return false;
#undef DO_
}

void getLatestVersionRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:DFMS.ROUTE.getLatestVersionRequest)
  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:DFMS.ROUTE.getLatestVersionRequest)
}

::google::protobuf::uint8* getLatestVersionRequest::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:DFMS.ROUTE.getLatestVersionRequest)
  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:DFMS.ROUTE.getLatestVersionRequest)
  return target;
}

int getLatestVersionRequest::ByteSize() const {
  int total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void getLatestVersionRequest::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const getLatestVersionRequest* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const getLatestVersionRequest*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void getLatestVersionRequest::MergeFrom(const getLatestVersionRequest& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void getLatestVersionRequest::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void getLatestVersionRequest::CopyFrom(const getLatestVersionRequest& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool getLatestVersionRequest::IsInitialized() const {

  return true;
}

void getLatestVersionRequest::Swap(getLatestVersionRequest* other) {
  if (other == this) return;
  InternalSwap(other);
}
void getLatestVersionRequest::InternalSwap(getLatestVersionRequest* other) {
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata getLatestVersionRequest::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = getLatestVersionRequest_descriptor_;
  metadata.reflection = getLatestVersionRequest_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int getLatestVersionResponse::kVersionNoFieldNumber;
const int getLatestVersionResponse::kVersionUpdateMsgFieldNumber;
const int getLatestVersionResponse::kErrorCodeFieldNumber;
#endif  // !_MSC_VER

getLatestVersionResponse::getLatestVersionResponse()
  : ::google::protobuf::Message() , _internal_metadata_(NULL)  {
  SharedCtor();
  // @@protoc_insertion_point(constructor:DFMS.ROUTE.getLatestVersionResponse)
}

void getLatestVersionResponse::InitAsDefaultInstance() {
}

getLatestVersionResponse::getLatestVersionResponse(const getLatestVersionResponse& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:DFMS.ROUTE.getLatestVersionResponse)
}

void getLatestVersionResponse::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  versionno_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  versionupdatemsg_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  errorcode_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

getLatestVersionResponse::~getLatestVersionResponse() {
  // @@protoc_insertion_point(destructor:DFMS.ROUTE.getLatestVersionResponse)
  SharedDtor();
}

void getLatestVersionResponse::SharedDtor() {
  versionno_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  versionupdatemsg_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void getLatestVersionResponse::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* getLatestVersionResponse::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return getLatestVersionResponse_descriptor_;
}

const getLatestVersionResponse& getLatestVersionResponse::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_route_2eproto();
  return *default_instance_;
}

getLatestVersionResponse* getLatestVersionResponse::default_instance_ = NULL;

getLatestVersionResponse* getLatestVersionResponse::New(::google::protobuf::Arena* arena) const {
  getLatestVersionResponse* n = new getLatestVersionResponse;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void getLatestVersionResponse::Clear() {
  if (_has_bits_[0 / 32] & 7) {
    if (has_versionno()) {
      versionno_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
    if (has_versionupdatemsg()) {
      versionupdatemsg_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
    errorcode_ = 0u;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool getLatestVersionResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:DFMS.ROUTE.getLatestVersionResponse)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string versionNo = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_versionno()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->versionno().data(), this->versionno().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "DFMS.ROUTE.getLatestVersionResponse.versionNo");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_versionUpdateMsg;
        break;
      }

      // optional string versionUpdateMsg = 2;
      case 2: {
        if (tag == 18) {
         parse_versionUpdateMsg:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_versionupdatemsg()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->versionupdatemsg().data(), this->versionupdatemsg().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "DFMS.ROUTE.getLatestVersionResponse.versionUpdateMsg");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_errorCode;
        break;
      }

      // optional uint32 errorCode = 3;
      case 3: {
        if (tag == 24) {
         parse_errorCode:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &errorcode_)));
          set_has_errorcode();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:DFMS.ROUTE.getLatestVersionResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:DFMS.ROUTE.getLatestVersionResponse)
  return false;
#undef DO_
}

void getLatestVersionResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:DFMS.ROUTE.getLatestVersionResponse)
  // optional string versionNo = 1;
  if (has_versionno()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->versionno().data(), this->versionno().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "DFMS.ROUTE.getLatestVersionResponse.versionNo");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->versionno(), output);
  }

  // optional string versionUpdateMsg = 2;
  if (has_versionupdatemsg()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->versionupdatemsg().data(), this->versionupdatemsg().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "DFMS.ROUTE.getLatestVersionResponse.versionUpdateMsg");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->versionupdatemsg(), output);
  }

  // optional uint32 errorCode = 3;
  if (has_errorcode()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(3, this->errorcode(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:DFMS.ROUTE.getLatestVersionResponse)
}

::google::protobuf::uint8* getLatestVersionResponse::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:DFMS.ROUTE.getLatestVersionResponse)
  // optional string versionNo = 1;
  if (has_versionno()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->versionno().data(), this->versionno().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "DFMS.ROUTE.getLatestVersionResponse.versionNo");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->versionno(), target);
  }

  // optional string versionUpdateMsg = 2;
  if (has_versionupdatemsg()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->versionupdatemsg().data(), this->versionupdatemsg().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "DFMS.ROUTE.getLatestVersionResponse.versionUpdateMsg");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->versionupdatemsg(), target);
  }

  // optional uint32 errorCode = 3;
  if (has_errorcode()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(3, this->errorcode(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:DFMS.ROUTE.getLatestVersionResponse)
  return target;
}

int getLatestVersionResponse::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & 7) {
    // optional string versionNo = 1;
    if (has_versionno()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->versionno());
    }

    // optional string versionUpdateMsg = 2;
    if (has_versionupdatemsg()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->versionupdatemsg());
    }

    // optional uint32 errorCode = 3;
    if (has_errorcode()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->errorcode());
    }

  }
  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void getLatestVersionResponse::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const getLatestVersionResponse* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const getLatestVersionResponse*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void getLatestVersionResponse::MergeFrom(const getLatestVersionResponse& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_versionno()) {
      set_has_versionno();
      versionno_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.versionno_);
    }
    if (from.has_versionupdatemsg()) {
      set_has_versionupdatemsg();
      versionupdatemsg_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.versionupdatemsg_);
    }
    if (from.has_errorcode()) {
      set_errorcode(from.errorcode());
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void getLatestVersionResponse::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void getLatestVersionResponse::CopyFrom(const getLatestVersionResponse& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool getLatestVersionResponse::IsInitialized() const {

  return true;
}

void getLatestVersionResponse::Swap(getLatestVersionResponse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void getLatestVersionResponse::InternalSwap(getLatestVersionResponse* other) {
  versionno_.Swap(&other->versionno_);
  versionupdatemsg_.Swap(&other->versionupdatemsg_);
  std::swap(errorcode_, other->errorcode_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata getLatestVersionResponse::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = getLatestVersionResponse_descriptor_;
  metadata.reflection = getLatestVersionResponse_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int userLoginRequest::kUsernameFieldNumber;
const int userLoginRequest::kPasswordFieldNumber;
const int userLoginRequest::kMacAddressFieldNumber;
#endif  // !_MSC_VER

userLoginRequest::userLoginRequest()
  : ::google::protobuf::Message() , _internal_metadata_(NULL)  {
  SharedCtor();
  // @@protoc_insertion_point(constructor:DFMS.ROUTE.userLoginRequest)
}

void userLoginRequest::InitAsDefaultInstance() {
}

userLoginRequest::userLoginRequest(const userLoginRequest& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:DFMS.ROUTE.userLoginRequest)
}

void userLoginRequest::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  username_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  password_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  macaddress_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

userLoginRequest::~userLoginRequest() {
  // @@protoc_insertion_point(destructor:DFMS.ROUTE.userLoginRequest)
  SharedDtor();
}

void userLoginRequest::SharedDtor() {
  username_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  password_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  macaddress_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void userLoginRequest::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* userLoginRequest::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return userLoginRequest_descriptor_;
}

const userLoginRequest& userLoginRequest::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_route_2eproto();
  return *default_instance_;
}

userLoginRequest* userLoginRequest::default_instance_ = NULL;

userLoginRequest* userLoginRequest::New(::google::protobuf::Arena* arena) const {
  userLoginRequest* n = new userLoginRequest;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void userLoginRequest::Clear() {
  if (_has_bits_[0 / 32] & 7) {
    if (has_username()) {
      username_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
    if (has_password()) {
      password_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
    if (has_macaddress()) {
      macaddress_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool userLoginRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:DFMS.ROUTE.userLoginRequest)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string username = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_username()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->username().data(), this->username().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "DFMS.ROUTE.userLoginRequest.username");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_password;
        break;
      }

      // optional string password = 2;
      case 2: {
        if (tag == 18) {
         parse_password:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_password()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->password().data(), this->password().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "DFMS.ROUTE.userLoginRequest.password");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_macAddress;
        break;
      }

      // optional string macAddress = 3;
      case 3: {
        if (tag == 26) {
         parse_macAddress:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_macaddress()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->macaddress().data(), this->macaddress().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "DFMS.ROUTE.userLoginRequest.macAddress");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:DFMS.ROUTE.userLoginRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:DFMS.ROUTE.userLoginRequest)
  return false;
#undef DO_
}

void userLoginRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:DFMS.ROUTE.userLoginRequest)
  // optional string username = 1;
  if (has_username()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->username().data(), this->username().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "DFMS.ROUTE.userLoginRequest.username");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->username(), output);
  }

  // optional string password = 2;
  if (has_password()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->password().data(), this->password().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "DFMS.ROUTE.userLoginRequest.password");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->password(), output);
  }

  // optional string macAddress = 3;
  if (has_macaddress()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->macaddress().data(), this->macaddress().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "DFMS.ROUTE.userLoginRequest.macAddress");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->macaddress(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:DFMS.ROUTE.userLoginRequest)
}

::google::protobuf::uint8* userLoginRequest::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:DFMS.ROUTE.userLoginRequest)
  // optional string username = 1;
  if (has_username()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->username().data(), this->username().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "DFMS.ROUTE.userLoginRequest.username");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->username(), target);
  }

  // optional string password = 2;
  if (has_password()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->password().data(), this->password().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "DFMS.ROUTE.userLoginRequest.password");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->password(), target);
  }

  // optional string macAddress = 3;
  if (has_macaddress()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->macaddress().data(), this->macaddress().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "DFMS.ROUTE.userLoginRequest.macAddress");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->macaddress(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:DFMS.ROUTE.userLoginRequest)
  return target;
}

int userLoginRequest::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & 7) {
    // optional string username = 1;
    if (has_username()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->username());
    }

    // optional string password = 2;
    if (has_password()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->password());
    }

    // optional string macAddress = 3;
    if (has_macaddress()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->macaddress());
    }

  }
  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void userLoginRequest::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const userLoginRequest* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const userLoginRequest*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void userLoginRequest::MergeFrom(const userLoginRequest& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_username()) {
      set_has_username();
      username_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.username_);
    }
    if (from.has_password()) {
      set_has_password();
      password_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.password_);
    }
    if (from.has_macaddress()) {
      set_has_macaddress();
      macaddress_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.macaddress_);
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void userLoginRequest::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void userLoginRequest::CopyFrom(const userLoginRequest& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool userLoginRequest::IsInitialized() const {

  return true;
}

void userLoginRequest::Swap(userLoginRequest* other) {
  if (other == this) return;
  InternalSwap(other);
}
void userLoginRequest::InternalSwap(userLoginRequest* other) {
  username_.Swap(&other->username_);
  password_.Swap(&other->password_);
  macaddress_.Swap(&other->macaddress_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata userLoginRequest::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = userLoginRequest_descriptor_;
  metadata.reflection = userLoginRequest_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int userLoginResponse::kUsernameFieldNumber;
const int userLoginResponse::kSessionIdFieldNumber;
const int userLoginResponse::kLoginTimeFieldNumber;
const int userLoginResponse::kErrorCodeFieldNumber;
#endif  // !_MSC_VER

userLoginResponse::userLoginResponse()
  : ::google::protobuf::Message() , _internal_metadata_(NULL)  {
  SharedCtor();
  // @@protoc_insertion_point(constructor:DFMS.ROUTE.userLoginResponse)
}

void userLoginResponse::InitAsDefaultInstance() {
}

userLoginResponse::userLoginResponse(const userLoginResponse& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:DFMS.ROUTE.userLoginResponse)
}

void userLoginResponse::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  username_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  sessionid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  logintime_ = GOOGLE_ULONGLONG(0);
  errorcode_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

userLoginResponse::~userLoginResponse() {
  // @@protoc_insertion_point(destructor:DFMS.ROUTE.userLoginResponse)
  SharedDtor();
}

void userLoginResponse::SharedDtor() {
  username_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  sessionid_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void userLoginResponse::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* userLoginResponse::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return userLoginResponse_descriptor_;
}

const userLoginResponse& userLoginResponse::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_route_2eproto();
  return *default_instance_;
}

userLoginResponse* userLoginResponse::default_instance_ = NULL;

userLoginResponse* userLoginResponse::New(::google::protobuf::Arena* arena) const {
  userLoginResponse* n = new userLoginResponse;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void userLoginResponse::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<userLoginResponse*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  if (_has_bits_[0 / 32] & 15) {
    ZR_(logintime_, errorcode_);
    if (has_username()) {
      username_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
    if (has_sessionid()) {
      sessionid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
  }

#undef OFFSET_OF_FIELD_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool userLoginResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:DFMS.ROUTE.userLoginResponse)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string username = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_username()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->username().data(), this->username().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "DFMS.ROUTE.userLoginResponse.username");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_sessionId;
        break;
      }

      // optional string sessionId = 2;
      case 2: {
        if (tag == 18) {
         parse_sessionId:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_sessionid()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->sessionid().data(), this->sessionid().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "DFMS.ROUTE.userLoginResponse.sessionId");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_loginTime;
        break;
      }

      // optional uint64 loginTime = 3;
      case 3: {
        if (tag == 24) {
         parse_loginTime:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &logintime_)));
          set_has_logintime();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(32)) goto parse_errorCode;
        break;
      }

      // optional uint32 errorCode = 4;
      case 4: {
        if (tag == 32) {
         parse_errorCode:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &errorcode_)));
          set_has_errorcode();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:DFMS.ROUTE.userLoginResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:DFMS.ROUTE.userLoginResponse)
  return false;
#undef DO_
}

void userLoginResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:DFMS.ROUTE.userLoginResponse)
  // optional string username = 1;
  if (has_username()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->username().data(), this->username().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "DFMS.ROUTE.userLoginResponse.username");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->username(), output);
  }

  // optional string sessionId = 2;
  if (has_sessionid()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->sessionid().data(), this->sessionid().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "DFMS.ROUTE.userLoginResponse.sessionId");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->sessionid(), output);
  }

  // optional uint64 loginTime = 3;
  if (has_logintime()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(3, this->logintime(), output);
  }

  // optional uint32 errorCode = 4;
  if (has_errorcode()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(4, this->errorcode(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:DFMS.ROUTE.userLoginResponse)
}

::google::protobuf::uint8* userLoginResponse::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:DFMS.ROUTE.userLoginResponse)
  // optional string username = 1;
  if (has_username()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->username().data(), this->username().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "DFMS.ROUTE.userLoginResponse.username");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->username(), target);
  }

  // optional string sessionId = 2;
  if (has_sessionid()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->sessionid().data(), this->sessionid().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "DFMS.ROUTE.userLoginResponse.sessionId");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->sessionid(), target);
  }

  // optional uint64 loginTime = 3;
  if (has_logintime()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(3, this->logintime(), target);
  }

  // optional uint32 errorCode = 4;
  if (has_errorcode()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(4, this->errorcode(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:DFMS.ROUTE.userLoginResponse)
  return target;
}

int userLoginResponse::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & 15) {
    // optional string username = 1;
    if (has_username()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->username());
    }

    // optional string sessionId = 2;
    if (has_sessionid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->sessionid());
    }

    // optional uint64 loginTime = 3;
    if (has_logintime()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt64Size(
          this->logintime());
    }

    // optional uint32 errorCode = 4;
    if (has_errorcode()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->errorcode());
    }

  }
  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void userLoginResponse::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const userLoginResponse* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const userLoginResponse*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void userLoginResponse::MergeFrom(const userLoginResponse& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_username()) {
      set_has_username();
      username_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.username_);
    }
    if (from.has_sessionid()) {
      set_has_sessionid();
      sessionid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.sessionid_);
    }
    if (from.has_logintime()) {
      set_logintime(from.logintime());
    }
    if (from.has_errorcode()) {
      set_errorcode(from.errorcode());
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void userLoginResponse::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void userLoginResponse::CopyFrom(const userLoginResponse& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool userLoginResponse::IsInitialized() const {

  return true;
}

void userLoginResponse::Swap(userLoginResponse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void userLoginResponse::InternalSwap(userLoginResponse* other) {
  username_.Swap(&other->username_);
  sessionid_.Swap(&other->sessionid_);
  std::swap(logintime_, other->logintime_);
  std::swap(errorcode_, other->errorcode_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata userLoginResponse::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = userLoginResponse_descriptor_;
  metadata.reflection = userLoginResponse_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int tFile::kFileNameFieldNumber;
const int tFile::kFileTypeFieldNumber;
const int tFile::kFilePermisFieldNumber;
#endif  // !_MSC_VER

tFile::tFile()
  : ::google::protobuf::Message() , _internal_metadata_(NULL)  {
  SharedCtor();
  // @@protoc_insertion_point(constructor:DFMS.ROUTE.tFile)
}

void tFile::InitAsDefaultInstance() {
}

tFile::tFile(const tFile& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:DFMS.ROUTE.tFile)
}

void tFile::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  filename_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  filetype_ = 0;
  filepermis_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

tFile::~tFile() {
  // @@protoc_insertion_point(destructor:DFMS.ROUTE.tFile)
  SharedDtor();
}

void tFile::SharedDtor() {
  filename_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void tFile::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* tFile::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return tFile_descriptor_;
}

const tFile& tFile::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_route_2eproto();
  return *default_instance_;
}

tFile* tFile::default_instance_ = NULL;

tFile* tFile::New(::google::protobuf::Arena* arena) const {
  tFile* n = new tFile;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void tFile::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<tFile*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  if (_has_bits_[0 / 32] & 7) {
    ZR_(filetype_, filepermis_);
    if (has_filename()) {
      filename_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
  }

#undef OFFSET_OF_FIELD_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool tFile::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:DFMS.ROUTE.tFile)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string fileName = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_filename()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->filename().data(), this->filename().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "DFMS.ROUTE.tFile.fileName");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_fileType;
        break;
      }

      // optional .DFMS.ROUTE.eFileType fileType = 2;
      case 2: {
        if (tag == 16) {
         parse_fileType:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::DFMS::ROUTE::eFileType_IsValid(value)) {
            set_filetype(static_cast< ::DFMS::ROUTE::eFileType >(value));
          } else {
            mutable_unknown_fields()->AddVarint(2, value);
          }
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_filePermis;
        break;
      }

      // optional .DFMS.ROUTE.eFilePermis filePermis = 3;
      case 3: {
        if (tag == 24) {
         parse_filePermis:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::DFMS::ROUTE::eFilePermis_IsValid(value)) {
            set_filepermis(static_cast< ::DFMS::ROUTE::eFilePermis >(value));
          } else {
            mutable_unknown_fields()->AddVarint(3, value);
          }
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:DFMS.ROUTE.tFile)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:DFMS.ROUTE.tFile)
  return false;
#undef DO_
}

void tFile::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:DFMS.ROUTE.tFile)
  // optional string fileName = 1;
  if (has_filename()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->filename().data(), this->filename().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "DFMS.ROUTE.tFile.fileName");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->filename(), output);
  }

  // optional .DFMS.ROUTE.eFileType fileType = 2;
  if (has_filetype()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      2, this->filetype(), output);
  }

  // optional .DFMS.ROUTE.eFilePermis filePermis = 3;
  if (has_filepermis()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      3, this->filepermis(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:DFMS.ROUTE.tFile)
}

::google::protobuf::uint8* tFile::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:DFMS.ROUTE.tFile)
  // optional string fileName = 1;
  if (has_filename()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->filename().data(), this->filename().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "DFMS.ROUTE.tFile.fileName");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->filename(), target);
  }

  // optional .DFMS.ROUTE.eFileType fileType = 2;
  if (has_filetype()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      2, this->filetype(), target);
  }

  // optional .DFMS.ROUTE.eFilePermis filePermis = 3;
  if (has_filepermis()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      3, this->filepermis(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:DFMS.ROUTE.tFile)
  return target;
}

int tFile::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & 7) {
    // optional string fileName = 1;
    if (has_filename()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->filename());
    }

    // optional .DFMS.ROUTE.eFileType fileType = 2;
    if (has_filetype()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->filetype());
    }

    // optional .DFMS.ROUTE.eFilePermis filePermis = 3;
    if (has_filepermis()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->filepermis());
    }

  }
  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void tFile::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const tFile* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const tFile*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void tFile::MergeFrom(const tFile& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_filename()) {
      set_has_filename();
      filename_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.filename_);
    }
    if (from.has_filetype()) {
      set_filetype(from.filetype());
    }
    if (from.has_filepermis()) {
      set_filepermis(from.filepermis());
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void tFile::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void tFile::CopyFrom(const tFile& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool tFile::IsInitialized() const {

  return true;
}

void tFile::Swap(tFile* other) {
  if (other == this) return;
  InternalSwap(other);
}
void tFile::InternalSwap(tFile* other) {
  filename_.Swap(&other->filename_);
  std::swap(filetype_, other->filetype_);
  std::swap(filepermis_, other->filepermis_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata tFile::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = tFile_descriptor_;
  metadata.reflection = tFile_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int getDirFilesNameRequest::kReqIdFieldNumber;
const int getDirFilesNameRequest::kAuthUUIDFieldNumber;
const int getDirFilesNameRequest::kDirStrFieldNumber;
#endif  // !_MSC_VER

getDirFilesNameRequest::getDirFilesNameRequest()
  : ::google::protobuf::Message() , _internal_metadata_(NULL)  {
  SharedCtor();
  // @@protoc_insertion_point(constructor:DFMS.ROUTE.getDirFilesNameRequest)
}

void getDirFilesNameRequest::InitAsDefaultInstance() {
}

getDirFilesNameRequest::getDirFilesNameRequest(const getDirFilesNameRequest& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:DFMS.ROUTE.getDirFilesNameRequest)
}

void getDirFilesNameRequest::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  reqid_ = 0u;
  authuuid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  dirstr_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

getDirFilesNameRequest::~getDirFilesNameRequest() {
  // @@protoc_insertion_point(destructor:DFMS.ROUTE.getDirFilesNameRequest)
  SharedDtor();
}

void getDirFilesNameRequest::SharedDtor() {
  authuuid_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  dirstr_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void getDirFilesNameRequest::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* getDirFilesNameRequest::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return getDirFilesNameRequest_descriptor_;
}

const getDirFilesNameRequest& getDirFilesNameRequest::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_route_2eproto();
  return *default_instance_;
}

getDirFilesNameRequest* getDirFilesNameRequest::default_instance_ = NULL;

getDirFilesNameRequest* getDirFilesNameRequest::New(::google::protobuf::Arena* arena) const {
  getDirFilesNameRequest* n = new getDirFilesNameRequest;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void getDirFilesNameRequest::Clear() {
  if (_has_bits_[0 / 32] & 7) {
    reqid_ = 0u;
    if (has_authuuid()) {
      authuuid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
    if (has_dirstr()) {
      dirstr_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool getDirFilesNameRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:DFMS.ROUTE.getDirFilesNameRequest)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional uint32 reqId = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &reqid_)));
          set_has_reqid();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_authUUID;
        break;
      }

      // optional string authUUID = 2;
      case 2: {
        if (tag == 18) {
         parse_authUUID:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_authuuid()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->authuuid().data(), this->authuuid().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "DFMS.ROUTE.getDirFilesNameRequest.authUUID");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_dirStr;
        break;
      }

      // optional string dirStr = 3;
      case 3: {
        if (tag == 26) {
         parse_dirStr:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_dirstr()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->dirstr().data(), this->dirstr().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "DFMS.ROUTE.getDirFilesNameRequest.dirStr");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:DFMS.ROUTE.getDirFilesNameRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:DFMS.ROUTE.getDirFilesNameRequest)
  return false;
#undef DO_
}

void getDirFilesNameRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:DFMS.ROUTE.getDirFilesNameRequest)
  // optional uint32 reqId = 1;
  if (has_reqid()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->reqid(), output);
  }

  // optional string authUUID = 2;
  if (has_authuuid()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->authuuid().data(), this->authuuid().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "DFMS.ROUTE.getDirFilesNameRequest.authUUID");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->authuuid(), output);
  }

  // optional string dirStr = 3;
  if (has_dirstr()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->dirstr().data(), this->dirstr().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "DFMS.ROUTE.getDirFilesNameRequest.dirStr");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->dirstr(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:DFMS.ROUTE.getDirFilesNameRequest)
}

::google::protobuf::uint8* getDirFilesNameRequest::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:DFMS.ROUTE.getDirFilesNameRequest)
  // optional uint32 reqId = 1;
  if (has_reqid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->reqid(), target);
  }

  // optional string authUUID = 2;
  if (has_authuuid()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->authuuid().data(), this->authuuid().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "DFMS.ROUTE.getDirFilesNameRequest.authUUID");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->authuuid(), target);
  }

  // optional string dirStr = 3;
  if (has_dirstr()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->dirstr().data(), this->dirstr().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "DFMS.ROUTE.getDirFilesNameRequest.dirStr");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->dirstr(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:DFMS.ROUTE.getDirFilesNameRequest)
  return target;
}

int getDirFilesNameRequest::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & 7) {
    // optional uint32 reqId = 1;
    if (has_reqid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->reqid());
    }

    // optional string authUUID = 2;
    if (has_authuuid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->authuuid());
    }

    // optional string dirStr = 3;
    if (has_dirstr()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->dirstr());
    }

  }
  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void getDirFilesNameRequest::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const getDirFilesNameRequest* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const getDirFilesNameRequest*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void getDirFilesNameRequest::MergeFrom(const getDirFilesNameRequest& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_reqid()) {
      set_reqid(from.reqid());
    }
    if (from.has_authuuid()) {
      set_has_authuuid();
      authuuid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.authuuid_);
    }
    if (from.has_dirstr()) {
      set_has_dirstr();
      dirstr_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.dirstr_);
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void getDirFilesNameRequest::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void getDirFilesNameRequest::CopyFrom(const getDirFilesNameRequest& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool getDirFilesNameRequest::IsInitialized() const {

  return true;
}

void getDirFilesNameRequest::Swap(getDirFilesNameRequest* other) {
  if (other == this) return;
  InternalSwap(other);
}
void getDirFilesNameRequest::InternalSwap(getDirFilesNameRequest* other) {
  std::swap(reqid_, other->reqid_);
  authuuid_.Swap(&other->authuuid_);
  dirstr_.Swap(&other->dirstr_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata getDirFilesNameRequest::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = getDirFilesNameRequest_descriptor_;
  metadata.reflection = getDirFilesNameRequest_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int getDirFilesNameResponse::kReqIdFieldNumber;
const int getDirFilesNameResponse::kDirStrFieldNumber;
const int getDirFilesNameResponse::kFilesFieldNumber;
const int getDirFilesNameResponse::kErrorCodeFieldNumber;
#endif  // !_MSC_VER

getDirFilesNameResponse::getDirFilesNameResponse()
  : ::google::protobuf::Message() , _internal_metadata_(NULL)  {
  SharedCtor();
  // @@protoc_insertion_point(constructor:DFMS.ROUTE.getDirFilesNameResponse)
}

void getDirFilesNameResponse::InitAsDefaultInstance() {
}

getDirFilesNameResponse::getDirFilesNameResponse(const getDirFilesNameResponse& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:DFMS.ROUTE.getDirFilesNameResponse)
}

void getDirFilesNameResponse::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  reqid_ = 0u;
  dirstr_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  errorcode_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

getDirFilesNameResponse::~getDirFilesNameResponse() {
  // @@protoc_insertion_point(destructor:DFMS.ROUTE.getDirFilesNameResponse)
  SharedDtor();
}

void getDirFilesNameResponse::SharedDtor() {
  dirstr_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void getDirFilesNameResponse::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* getDirFilesNameResponse::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return getDirFilesNameResponse_descriptor_;
}

const getDirFilesNameResponse& getDirFilesNameResponse::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_route_2eproto();
  return *default_instance_;
}

getDirFilesNameResponse* getDirFilesNameResponse::default_instance_ = NULL;

getDirFilesNameResponse* getDirFilesNameResponse::New(::google::protobuf::Arena* arena) const {
  getDirFilesNameResponse* n = new getDirFilesNameResponse;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void getDirFilesNameResponse::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<getDirFilesNameResponse*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  if (_has_bits_[0 / 32] & 11) {
    ZR_(reqid_, errorcode_);
    if (has_dirstr()) {
      dirstr_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
  }

#undef OFFSET_OF_FIELD_
#undef ZR_

  files_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool getDirFilesNameResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:DFMS.ROUTE.getDirFilesNameResponse)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional uint32 reqId = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &reqid_)));
          set_has_reqid();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_dirStr;
        break;
      }

      // optional string dirStr = 2;
      case 2: {
        if (tag == 18) {
         parse_dirStr:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_dirstr()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->dirstr().data(), this->dirstr().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "DFMS.ROUTE.getDirFilesNameResponse.dirStr");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_files;
        break;
      }

      // repeated .DFMS.ROUTE.tFile files = 3;
      case 3: {
        if (tag == 26) {
         parse_files:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_files()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_files;
        if (input->ExpectTag(32)) goto parse_errorCode;
        break;
      }

      // optional uint32 errorCode = 4;
      case 4: {
        if (tag == 32) {
         parse_errorCode:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &errorcode_)));
          set_has_errorcode();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:DFMS.ROUTE.getDirFilesNameResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:DFMS.ROUTE.getDirFilesNameResponse)
  return false;
#undef DO_
}

void getDirFilesNameResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:DFMS.ROUTE.getDirFilesNameResponse)
  // optional uint32 reqId = 1;
  if (has_reqid()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->reqid(), output);
  }

  // optional string dirStr = 2;
  if (has_dirstr()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->dirstr().data(), this->dirstr().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "DFMS.ROUTE.getDirFilesNameResponse.dirStr");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->dirstr(), output);
  }

  // repeated .DFMS.ROUTE.tFile files = 3;
  for (unsigned int i = 0, n = this->files_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->files(i), output);
  }

  // optional uint32 errorCode = 4;
  if (has_errorcode()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(4, this->errorcode(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:DFMS.ROUTE.getDirFilesNameResponse)
}

::google::protobuf::uint8* getDirFilesNameResponse::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:DFMS.ROUTE.getDirFilesNameResponse)
  // optional uint32 reqId = 1;
  if (has_reqid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->reqid(), target);
  }

  // optional string dirStr = 2;
  if (has_dirstr()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->dirstr().data(), this->dirstr().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "DFMS.ROUTE.getDirFilesNameResponse.dirStr");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->dirstr(), target);
  }

  // repeated .DFMS.ROUTE.tFile files = 3;
  for (unsigned int i = 0, n = this->files_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        3, this->files(i), target);
  }

  // optional uint32 errorCode = 4;
  if (has_errorcode()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(4, this->errorcode(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:DFMS.ROUTE.getDirFilesNameResponse)
  return target;
}

int getDirFilesNameResponse::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & 11) {
    // optional uint32 reqId = 1;
    if (has_reqid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->reqid());
    }

    // optional string dirStr = 2;
    if (has_dirstr()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->dirstr());
    }

    // optional uint32 errorCode = 4;
    if (has_errorcode()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->errorcode());
    }

  }
  // repeated .DFMS.ROUTE.tFile files = 3;
  total_size += 1 * this->files_size();
  for (int i = 0; i < this->files_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->files(i));
  }

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void getDirFilesNameResponse::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const getDirFilesNameResponse* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const getDirFilesNameResponse*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void getDirFilesNameResponse::MergeFrom(const getDirFilesNameResponse& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  files_.MergeFrom(from.files_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_reqid()) {
      set_reqid(from.reqid());
    }
    if (from.has_dirstr()) {
      set_has_dirstr();
      dirstr_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.dirstr_);
    }
    if (from.has_errorcode()) {
      set_errorcode(from.errorcode());
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void getDirFilesNameResponse::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void getDirFilesNameResponse::CopyFrom(const getDirFilesNameResponse& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool getDirFilesNameResponse::IsInitialized() const {

  return true;
}

void getDirFilesNameResponse::Swap(getDirFilesNameResponse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void getDirFilesNameResponse::InternalSwap(getDirFilesNameResponse* other) {
  std::swap(reqid_, other->reqid_);
  dirstr_.Swap(&other->dirstr_);
  files_.UnsafeArenaSwap(&other->files_);
  std::swap(errorcode_, other->errorcode_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata getDirFilesNameResponse::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = getDirFilesNameResponse_descriptor_;
  metadata.reflection = getDirFilesNameResponse_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace ROUTE
}  // namespace DFMS

// @@protoc_insertion_point(global_scope)
